### ISSUE TITLE
Launch public consultation in English

### ISSUE THREAD

**Issue by jangondol** [ogpslovakia/ogpslovakia.github.io#2]
**TODO:**
- [x] Translate the survey (Google form) to English
- [x] Translate the announcement letter to English
- [x] Generate Bitly links (EN form + letter)
- [x] Add link to the home page
- [x] Notify all the intended recipients
- [x] Notify media (epsiplatform.eu)
